### ISSUE TITLE
Best way to get parent Post category

### ISSUE THREAD

**Issue by joepages** [yeesoft/yii2-yee-cms#10]
Hello @yeesoft what could be the best way to get the parent post category from \frontend\views\site\index ? 

Example: 

I have a Parent category: Lets called Services. 
I have a child category (which parent category is Services): Lets called Drilling.

What is the best way to get Services category instead of child category? 

when coded like: 

`$post->category['title']`

it brings the child category instead of the parent category if child category is registered... Any suggestions? 

Regards, 
José

**Comment by yeesoft** [comment]
@joepages Hi! Thanks for your question.

Category model use https://github.com/paulzi/yii2-nested-intervals behavior. It gives very flexible tools to select posts and categories.

In your situation solution is `$post->category->parent->title`.
