### ISSUE TITLE
When deleting a category from Media and an album is already created error

### ISSUE THREAD

**Issue by joepages** [yeesoft/yii2-yee-cms#11]
Hello @yeesoft 

I tried to delete a category and done it successfully. Then went to albums an this image pop out.. 

I think there's missing some validator that prevent from deleting media categories if an album is related.

![screen shot 2016-04-15 at 7 47 11 am](https://cloud.githubusercontent.com/assets/583979/14561225/a9f2c2b4-02de-11e6-8b29-bf3bd80551a2.png)

**Comment by joepages** [comment]
Hello again @yeesoft 

I solved it with an if condition between lines 63 and 65.

![screen shot 2016-04-15 at 8 06 17 am](https://cloud.githubusercontent.com/assets/583979/14561621/51073eac-02e1-11e6-873d-91fde16e357b.png)

**Comment by yeesoft** [comment]
fixed
