### ISSUE TITLE
New feature required - Text Module

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#12]
Hi @yeesoft I think will be necessary a new feature on this cms, sometimes the users/developers could require the capability to define dynamic text blocks, like in the TEXT MODULE of EasyiiCMS http://easyiicms.com/docs/text

Please, can you create a new repository for that purpose?,  I'll submit the necessary chunk of code in a new pull request.

**Comment by yeesoft** [comment]
I created new module Blocks: https://github.com/yeesoft/yii2-yee-block
Do you have any suggestions how to improve or extend the functionality of this module?

**Comment by frankirox** [comment]
Hi @yeesoft this is perfect, I will use this module today, I will post suggestions soon if I have.
