### ISSUE TITLE
Adjustment required in post and page modules

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#13]
Hi @yeesoft I think will be necessary an adjustment, sometimes the users/developers could require the original image instead of the thumbnail  in posts and pages.

I'll submit a new pull request with the necessary chunk of code to preserve and recover the original image of one post and/or page.

**Comment by yeesoft** [comment]
@frankirox You can get original image by `$media->url`.

**Comment by frankirox** [comment]
@yeesoft understood, thank you!! 

@joepages take a look here.

**Comment by frankirox** [comment]
@yeesoft just a little more question, $media is an instance of what? Post?

because I need the original  image attached to the Post (the big one), currently I can get only the thumbnail (the small one) through the Post instance.

**Comment by yeesoft** [comment]
Oh, I got it. You mean thumbnail of the post.

I just pushed code that allow to do this. You should update yeesoft/yii2-yee-post module with composer. Then update your backend config file:

```
'modules'=>[
    'post' => [
        'class' => 'yeesoft\post\PostModule',
        'thumbnailSize' => 'original',
    ],
],

```

Look at this param ` yeesoft\post\PostModule::$thumbnailSize`, it should solve your problem
