### ISSUE TITLE
New feature required - Carousel Module 

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#14]
Hi @yeesoft I think will be necessary a new feature on this cms, sometimes the users/developers could require the capability to define carousels with dynamic images like in the CAROUSEL MODULE of EasyiiCMS http://easyiicms.com/docs/carousel

Please, can you create a new repository for that purpose?, I'll submit the necessary chunk of code in a new pull request.

**Comment by yeesoft** [comment]
@frankirox I just added Carousel widget for rendering Bootstrap Carousel with images from album in  Media module.

`use yeesoft\media\widgets\Carousel;`

Basic usage:
` echo Carousel::widget(['album' => 'carousel'])`

With custom views:
```
echo Carousel::widget([
     'album' => 'carousel',
     'contentView' => '@frontend/views/carousel/content',
     'captionView' => '@frontend/views/carousel/caption',
     'itemsOptions' => ['class' => 'some-class']
 ]);
```

**Comment by frankirox** [comment]
Looks like you are always one step forward, @yeesoft awesome! this is great job!, thank you.

@joepages take a look here.
