### ISSUE TITLE
I can't change the admin password after complete the installation

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#15]
I can't change the admin password after complete the installation.

**Comment by yeesoft** [comment]
I added tool that allow to init root user after application instalation.

Please, check 6th step of https://github.com/yeesoft/yii2-yee-cms/blob/master/README.md

Please, check if you have this new file https://github.com/yeesoft/yii2-yee-cms/blob/master/console/controllers/InitAdminController.php in your application in /console/controllers/ folder
