### ISSUE TITLE
Notification Flash

### ISSUE THREAD

**Issue by loveorigami** [yeesoft/yii2-yee-cms#16]
Просматриваю некоторые наработки в вашей cms. Нечто похожее пишу для себя. 
Часто возникает вопрос показывать флеш-сообщение после той или иной операции, включая ajax запросы. 
Для своей cms я написал небольшой модуль, который полностью решает эту задачу.
https://github.com/loveorigami/yii2-notification-wrapper

Можно использовать вместо 
https://github.com/yeesoft/yii2-yee-cms/blob/master/common/widgets/Alert.php

**Comment by yeesoft** [comment]
Standard alerts cover all functionality that is needed on back-end side.
But you can freely use what plugins you want on front-end part of CMS.
