### ISSUE TITLE
during installation  I am getting some dependencies issues

### ISSUE THREAD

**Issue by hikmat30ce** [yeesoft/yii2-yee-cms#18]
Problem 1
    - Installation request for yeesoft/yii2-yee-core * -> satisfiable by yeesoft/yii2-yee-core[dev-master].
    - yeesoft/yii2-yee-core dev-master requires bower-asset/metismenu * -> no matching package found.
  Problem 2
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.6, 2.0.7, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by yeesoft** [comment]
Maybe there are outdated asset-plugin, try to update it  `composer global require "fxp/composer-asset-plugin:~1.1.0"`

**Comment by hikmat30ce** [comment]
issue resolved!
