### ISSUE TITLE
migration m150319_150657_alter_user_table failed on postgresql

### ISSUE THREAD

**Issue by Insolita** [yeesoft/yii2-yee-cms#21]
*** applying m150319_150657_alter_user_table
    > add column superadmin smallint(6) DEFAULT '0' AFTER `status` to table user ...Exception: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "AFTER"
![migrate_error](https://cloud.githubusercontent.com/assets/1847402/14802700/ea71b1bc-0b8d-11e6-91b9-30eab765df0d.jpg)

postgresql not support change column order

**Comment by yeesoft** [comment]
Migrations have been fixed. There are still issues caused on pgsql db. Will be fixed in #29 .
