### ISSUE TITLE
login 404

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#23]
Hi @yeesoft, any idea about why I got a 404 error in frontend after being automatically redirected to the login page  as guest?

en/auth/login works fine, but the system is redirecting to by default /auth/login and I got 404, is a bit weird.

**Comment by joepages** [comment]
Hello @yeesoft I'm having the same trouble. I've tried to solved this in many ways but I always get errors...

I did what's in the image attached and works fine but when clicking any other link of the menu get an ugly url: 
![screen shot 2016-04-30 at 8 52 45 am](https://cloud.githubusercontent.com/assets/583979/14936019/0d3f2370-0eb1-11e6-8d68-0b61ad93c48d.png)

Example of ugly url after running the code of the image: http://centos-emcar.dev/auth/site/index?language=en

Any ideas how to solve this? 

Regards, 
Jose

**Comment by frankirox** [comment]
solved, was a little typo in the home Url (missing slash)

<?= Html::a(Yii::t('yee/frontend', 'Home'), ['**/**site/index']); ?>

and another thing, I've added an additional parameter to an existent rule in frontend UrlManager

 'rules' => array(
                '<module:auth>/<action:(logout|captcha**|login**)>' => '<module>/default/<action>',
                '<module:auth>/<action:(oauth)>/<authclient:\w+>' => '<module>/default/<action>',
            ),
            'multilingualRules' => [
                '<controller:category>/<slug:[\w \-]+>' => '<controller>/index',
                '<controller:category>' => '<controller>/index',
                '<slug:[\w \-]+>' => 'site/index/',
                '/' => 'site/index',
                '<action:[\w \-]+>' => 'site/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ],
