### ISSUE TITLE
Where documentation for this CMS ?

### ISSUE THREAD

**Issue by adiramardiani** [yeesoft/yii2-yee-cms#26]
I very apreciated with this cms, the feature is very usefull for me, but (sorry) if I compared with other, one the important thing is `documentation`.

Like getting data, function list, etc
Sorry if i compared with [this](http://easyiicms.com/docs/article), the documentation is good. But still. yee cms is my choice :)

**Comment by yeesoft** [comment]
I have added autogenerated documentation: http://www.yee-soft.com/docs/ . This docs will be improved in the future.

**Comment by adiramardiani** [comment]
Ok, thanks but active menu not in `about` :)

**Comment by yeesoft** [comment]
fixed
