### ISSUE TITLE
Can't access admin on cloud9

### ISSUE THREAD

**Issue by hdushku** [yeesoft/yii2-yee-cms#27]
I installed the app but can't access admin on cloud9
I'm getting:
Not Found (#404)
Page not found.

**Comment by yeesoft** [comment]
Need more details. Do you see any errors?

**Comment by hdushku** [comment]
I executed the init command and selected dev as environment but still does not show the error, just not found.
thanks

**Comment by yeesoft** [comment]
Maybe there are some problems with files' owner or permissions. Try to apply correct permissions to your files:

`chown -R www-data:www-data /var/www/site.com`
`chmod -R g+rw /var/www/site.com`

**Comment by hdushku** [comment]
Thank you!
This is my config in cloud9 for frontend:

<VirtualHost *:8080>
    DocumentRoot /home/ubuntu/workspace/frontend/web
    ServerName https://${C9_HOSTNAME}:443

    LogLevel info

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /home/ubuntu/workspace/frontend/web>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
ServerName https://${C9_HOSTNAME}
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

What configuration should I make now?

**Comment by hdushku** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8830905/15569952/f24cd534-2333-11e6-9beb-a1d19b71ce93.jpg)

When i change the documentroot to backend shows me the above image.

**Comment by hdushku** [comment]
Just solved it by adding:

`
Alias /admin /home/ubuntu/workspace/backend/web
            <Directory /home/ubuntu/workspace/backend/web>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
            </Directory>
`
to the apache config
Thanks, great yii2 app startup

**Comment by hdushku** [comment]
The dashboard is shown but still when I try to access admin/page
shows me the frontend with Not Found (#404) error.

**Comment by hdushku** [comment]
I left the apache config as defaults and its working now.
