### ISSUE TITLE
Error: SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by hdushku** [yeesoft/yii2-yee-cms#3]
insert into seo ...Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxx.seo' doesn't exist
The SQL being executed was: INSERT INTO `seo` (`url`, `title`, `author`, `keywords`, `description`, `index`, `follow`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES ('/en', 'Homepage', 'Site Owner', 'yii2, cms, yeecms', 'Seo meta description', 1, 1, 1, 1, '1452544164', '1452545049')

**Comment by yeesoft** [comment]
You should apply seo module migrations:
`yii migrate --migrationPath=@vendor/yeesoft/yii2-yee-eav/migrations/`
