### ISSUE TITLE
Class yii\authclient\clients\GoogleOAuth does not exist

### ISSUE THREAD

**Issue by dkduyanh** [yeesoft/yii2-yee-cms#35]
After installation, I got an error when access login page (http://yeecms.local/auth/login)

Error details:
ReflectionException
Class yii\authclient\clients\GoogleOAuth does not exist

**Comment by yeesoft** [comment]
Use `yii\authclient\clients\Google` instead of `yii\authclient\clients\GoogleOAuth` in your config file.
