### ISSUE TITLE
Comment Post -  Submit Button "Post" disable

### ISSUE THREAD

**Issue by mysoundmagic** [yeesoft/yii2-yee-cms#37]
i cannot post comment as guest, after insert content, username and email submit button always disabled and after submit post as user show Invalid Configuration,  Language 'en-US' do not exist. how to fix it ? 
Log :
yii\base\InvalidConfigException: Language 'en-US' do not exist. in /var/www/yii2-yee-cms.dev/vendor/yiidoc/yii2-timeago/TimeAgo.php:66 Stack trace: #0 /var/www/yii2-yee-cms.dev/vendor/yiidoc/yii2-timeago/TimeAgo.php(54): yii\timeago\TimeAgo->registerLocale() #1 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Object.php(107): yii\timeago\TimeAgo->init() #2 [internal function]: yii\base\Object->__construct(Array) #3 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/di/Container.php(379): ReflectionClass->newInstanceArgs(Array) #4 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('yii\\timeago\\Tim...', Array, Array) #5 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yii\\timeago\\Tim...', Array, Array) #6 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Widget.php(101): yii\BaseYii::createObject(Array) #7 /var/www/yii2-yee-cms.dev/vendor/yeesoft/yii2-comments/widgets/views/comment.php(18): yii\base\Widget::widget(Array) #8 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/yii2-y...') #9 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/yii2-y...', Array) #10 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/yii2-y...', Array, NULL) #11 /var/www/yii2-yee-cms.dev/vendor/yeesoft/yii2-comments/widgets/views/comments.php(39): yii\base\View->render('comment', Array) #12 [internal function]: yii\base\View->{closure}(Object(yeesoft\comments\models\Comment), 2, 0, Object(yii\widgets\ListView)) #13 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/widgets/ListView.php(102): call_user_func(Object(Closure), Object(yeesoft\comments\models\Comment), 2, 0, Object(yii\widgets\ListView)) #14 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/widgets/ListView.php(77): yii\widgets\ListView->renderItem(Object(yeesoft\comments\models\Comment), 2, 0) #15 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/widgets/BaseListView.php(151): yii\widgets\ListView->renderItems() #16 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/widgets/BaseListView.php(126): yii\widgets\BaseListView->renderSection('{items}') #17 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) #18 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/widgets/BaseListView.php(129): preg_replace_callback('/{\\w+}/', Object(Closure), '{items}<div cla...') #19 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Widget.php(102): yii\widgets\BaseListView->run() #20 /var/www/yii2-yee-cms.dev/vendor/yeesoft/yii2-comments/widgets/views/comments.php(35): yii\base\Widget::widget(Array) #21 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/yii2-y...') #22 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/yii2-y...', Array) #23 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/yii2-y...', Array, Object(yeesoft\comments\widgets\Comments)) #24 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Widget.php(195): yii\base\View->render('comments', Array, Object(yeesoft\comments\widgets\Comments)) #25 /var/www/yii2-yee-cms.dev/vendor/yeesoft/yii2-comments/widgets/Comments.php(76): yii\base\Widget->render('comments', Array) #26 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Widget.php(102): yeesoft\comments\widgets\Comments->run() #27 /var/www/yii2-yee-cms.dev/frontend/views/site/post.php(16): yii\base\Widget::widget(Array) #28 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/yii2-y...') #29 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/yii2-y...', Array) #30 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/yii2-y...', Array, Object(frontend\controllers\SiteController)) #31 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('post', Array, Object(frontend\controllers\SiteController)) #32 /var/www/yii2-yee-cms.dev/frontend/actions/PostAction.php(19): yii\base\Controller->render('post', Array) #33 /var/www/yii2-yee-cms.dev/frontend/controllers/SiteController.php(100): frontend\actions\PostAction->run() #34 [internal function]: frontend\controllers\SiteController->actionIndex('integer-id-ulla...') #35 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #36 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #37 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('index', Array) #38 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('site/index', Array) #39 /var/www/yii2-yee-cms.dev/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #40 /var/www/yii2-yee-cms.dev/frontend/web/index.php(18): yii\base\Application->run() #41 {main}

**Comment by yeesoft** [comment]
Fixed.
