### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by rammtw** [yeesoft/yii2-yee-cms#38]
Hi. How to change language? I'm trying to change in /common/config/params.php
`<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'version' => '0.1-a',
    'languages' => [
        'en-US' => 'English',
        'ru-RU' => 'Russian'
    ],
    'languageRedirects' => [
        'en-US' => 'en',
    ],
];
`
and in /commin/config/main.php change to
`
'language' => 'ru-RU',
`
And I get an error:

> Invalid language settings! Default application language should be included into `yeesoft\Yee::$languages` setting.

**Comment by bayuah** [comment]
So, what you did to resolve this? Come one!

**Comment by bayuah** [comment]
By the way.

If you're a Google searcher, the way to fix the problem is just set the component properties of Yee module.

Like this:

```
$config['components']['yee'] => [
		'languages' => ['id' => 'Bahasa Indonesia'],
		'languageRedirects' => ['id' => 'id'],
	],
];
```

I hope this will help somebody.

**Comment by baljinder1307** [comment]
?
