### ISSUE TITLE
I got errors everywhere with OwnerAccess::class, why?

### ISSUE THREAD

**Issue by joepages** [yeesoft/yii2-yee-cms#4]
here is a capture as an example. 
I'm running yeeCMS on CentOs 7 with PHP 5.4 

![screen shot 2016-04-04 at 12 08 33 pm](https://cloud.githubusercontent.com/assets/583979/14255481/051d6eac-fa5e-11e5-9d4b-d6e5fb66b62f.png)

**Comment by joepages** [comment]
found the error, PHP 5.4 don't have  ::class

**Comment by yeesoft** [comment]
Fixed
