### ISSUE TITLE
During migrating, Only 5 of 7 tables are successful.

### ISSUE THREAD

**Issue by mansi7771** [yeesoft/yii2-yee-cms#40]
I am new here. Please help me with this tiny issue. Thank you.
![image](https://cloud.githubusercontent.com/assets/18692751/22419109/ec0df198-e701-11e6-9e84-db1c96f1e831.png)

Failes migrations are:

Total 2 new migrations to be applied:
        m151121_091144_i18n_yee_source
        m160831_224932_alter_user_table

**Comment by yeesoft** [comment]
It looks like you have deleted some migrations before you run migration tool.
