### ISSUE TITLE
Access for Superadmin after intall

### ISSUE THREAD

**Issue by Tureckiy** [yeesoft/yii2-yee-cms#41]
Hi. How can I get acces to admin area for Superadmin (/admin route) After command 
` php yii init-admin.` here  i get http://joxi.ru/Drlz5nxiw0oW2P only simple admin user (I dont know role for this user now) and I want to get access to controll panell as on demo site. Thanks!

**Comment by yeesoft** [comment]
Just follow installation instructions and then go to `yoursite.com/admin`.  User created by `init-admin` has root access
