### ISSUE TITLE
The page isn’t redirecting properly admin backend

### ISSUE THREAD

**Issue by viturena** [yeesoft/yii2-yee-cms#42]
Am new to yee-cms
I created virtual host for both frontend and backend in my local computer.
the frontend _**frontend.local**_ part is working perfectly.
But I have problem accessing the backend.  I get the redirection error from mozilla firefox " The page isn’t redirecting properly" when accessing the _**backend.local**_  from my computer, also cleared cashes & browsing history  with no success,  I can't proceed with the backend login!
Is it a misconfiguration issue? I just followed the installation guideline, and I haven't changed any code so far.  
Looking for your help please!!

**Comment by yeesoft** [comment]
What do you mean 

> virtual host for both frontend and backend

?

There should be one host for yeecms. Try access to frontend.local/admin

**Comment by viturena** [comment]
Thank you for your quick reply,
I configured two vhosts for yeecms. one for frontend and other for backend. as shown in the attachment.  I think you meant I should remove the backend vhost configuration and access the backend part with maishafront.local/admin.  is this correct? 
![screenshot from 2017-02-27 18-18-53](https://cloud.githubusercontent.com/assets/964257/23366858/4ef3ff0a-fd19-11e6-9c3e-93e2eec81aaf.png)

**Comment by viturena** [comment]
I have also removed the backend vhost configuration and remained with one.. 
frontend, But I now get this error "Page not found"  when i access maishafront.local/admin

Anything I am missing here?

**Comment by yeesoft** [comment]
As I see you don't follow installation instruction.
Correct apache config is:
`<VirtualHost *:80>
   ServerName mysite.com
   ServerAlias www.mysite.com
   DocumentRoot "/var/www/mysite.com/"
   <Directory "/var/www/mysite.com/">
     AllowOverride All
   </Directory>
 </VirtualHost>`

**Comment by viturena** [comment]
Thank you very much, I followed instruction correctly, and now everything is working perfect

**Comment by viturena** [comment]
Thank you very much, I followed instruction correctly, and now everything is working perfect

**Comment by rossaddison** [comment]
This setup below gave me the above error aswell which I have managed to solve with much frustration. Can you spot my errors here? :(  Solution below :)

<VirtualHost *:80>
	ServerName yee-soft.dev.frontend
         ServerAlias yee-soft.dev.frontend
	DocumentRoot "d:/wamp29/www/yee-soft/frontend"
	<Directory  "d:/wamp29/www/yee-soft/frontend">
               
	</Directory>
</VirtualHost>

Notes: 
1.  I initially made the mistake of installing in document root  d:/wamp29/www/yee-soft/frontend. 
    Go one directory back to accomodate both frontend and backend.
2.  I forgot the forward slashes after yee-soft.
3.  I forgot AllowOverride All

Working setup as follows:
<VirtualHost *:80>
	ServerName yee-soft.dev
        ServerAlias yee-soft.dev
	DocumentRoot "d:/wamp29/www/yee-soft/"
	<Directory  "d:/wamp29/www/yee-soft/">
               AllowOverride All
	</Directory>
</VirtualHost>
