### ISSUE TITLE
Failure: Access to custom codes

### ISSUE THREAD

**Issue by viturena** [yeesoft/yii2-yee-cms#43]
I have generated codes with gii, and placed under backend/models, backend/controllers and backend/views. also added menu link under admin control panel to linking to controller ID. 
But am having problem accessing the generated codes. "Page not found error is displayed".
 Is this the right way to do with custom codes for both yeeCMS backend?
Can someone help how best place my custom codes and how to access via Url

I will appreciate any help

**Comment by yeesoft** [comment]
Have you added url rules in `backend/config/main.php`? There are lines:

'urlManager' => [
   ...
            'rules' => array(
                //add here local frontend controllers
                '<controller:(test)>' => '<controller>/index',
                '<controller:(test)>/<id:\d+>' => '<controller>/view',
                '<controller:(test)>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:(test)>/<action:\w+>' => '<controller>/<action>',
    ...

You must update these lines according to your new controller.
