### ISSUE TITLE
When working with multilingual fields using multiple single widget, widget wont display correctly

### ISSUE THREAD

**Issue by joepages** [yeesoft/yii2-yee-cms#44]
Hello guys! I've been working with YeeCMS quite a while now... And I have discovered a bug that i havent been able to fix... so, here it is..

I have a modal windows where I want to display dynamic custom fields, so I have my logic working just fine. The problem is when a widget is called more than once, it occurs that the framework assigns the same id for each field and for that reason it wont display correctly. So I've been trying to fix this on my own but I havent been able, so I'm asking for help. 

So in this three images you can see the problem without the multilingual tabs. I attach an screenshot of the code too.
![screen shot 2017-03-04 at 10 03 53 am](https://cloud.githubusercontent.com/assets/583979/23579365/72e7e078-00c2-11e7-96e3-77dd65980c3b.png)

In this image first form fields displaying correctly.
![screen shot 2017-03-04 at 10 05 12 am](https://cloud.githubusercontent.com/assets/583979/23579367/769e87d0-00c2-11e7-944c-659a01ab0c51.png)

in this image second form fields displaying not that good...
![screen shot 2017-03-04 at 10 06 12 am](https://cloud.githubusercontent.com/assets/583979/23579368/783f3332-00c2-11e7-90cd-45b9c3c7b6f7.png)

I really appreciate any help! 
 Thanks, 
Jose

**Comment by yeesoft** [comment]
@joepages Hi! Try this instruction to fix your issue:

1. Update `yeesoft/yii2-yee-core` module to the latest version (0.1.1)
2. Add custom input id that depends on the modal form, example:
`<?= $form->field($formModel, 'content')->widget(TinyMce::className(), ['options' => ['id' => "content_{$model->id}"]]); ?>`

Also, I recommend you to update all YeeCMS modules to ~0.1.0 version, like here [composer.json](https://github.com/yeesoft/yii2-yee-cms/blob/0.1.0/composer.json) in require section. Version 0.2.* will be incompatible with current version.

**Comment by joepages** [comment]
Hello @yeesoft !! 

I just tried what you told me and thats a negative. 

I'm going to try to describe the exact problem.

When you have any field (I'm using TinyMce because I need to be able to give format to the input text) that automatically generates its ID when its not defined the first input text comes out just fine but the second field can't display because it encounters the same ID than before. lets say for example: 

Field 1: short_description
field 2: description

short_description field is displaying fine in both languages but description won't display field as needed. 

So, after following your suggestion I assigned an ID to the field; whats happening now that it displays the first field on each language just fine, but the secondary language won't show as needed. 

![screen shot 2017-03-05 at 9 27 13 am](https://cloud.githubusercontent.com/assets/583979/23587571/f0812710-0185-11e7-83da-07011bbeb5fa.png)
![screen shot 2017-03-05 at 9 17 15 am](https://cloud.githubusercontent.com/assets/583979/23587572/f8712ae2-0185-11e7-9d15-e81c101ff1c0.png)

As I'm building a big customised open system for teaching, I was obligated to copy must of the YeeSoft modules from vendor to common or backend and I can¡t update yeesoft via composer, I do have the last version of yii2-yee-core 0.1.1. 

I really need to get this fixed and I haven't been able to find a way to do so... 

please help me, 

Regards, 
Jose

**Comment by yeesoft** [comment]
It seems that you done something wrong, because this instructions fix the problem with duplication of id.

1. Have you updated `yeesoft/yii2-yee-core` module to the latest version (0.1.1)?
2. Does your `ActiveForm` extends `yeesoft\widgets\ActiveForm`?

Look at [this code](https://github.com/yeesoft/yii2-yee-core/commit/2264664c96834afd8ede4b2d6c7436f3c63a9b73). This is the fix of the bug.

**Comment by joepages** [comment]
@yeesoft hello!!

Awesome work! Couldn't solve it by myself! 

Yes should have a timeline changes so we can see whats new. Perhaps it already exist and i don't know it. 

once again, thank you very much!

Regards,
José
