### ISSUE TITLE
 Installed it in a sub-directory in /var/www/html, got Not Found (#404) error.

### ISSUE THREAD

**Issue by laoheimao** [yeesoft/yii2-yee-cms#45]
I think the path is fixed in / , can you add an option to define the path of yee-cms installation?

**Comment by laoheimao** [comment]
Following is my .htaccess.
# prevent directory listings
Options -Indexes
# follow symbolic links
Options FollowSymlinks
RewriteEngine on
#RewriteBase /yeecms/mysite.com/

RewriteCond %{REQUEST_URI} ^/admin/$
RewriteRule ^(admin)/$ /$1 [R=301,L]
RewriteCond %{REQUEST_URI} ^/admin
RewriteRule ^admin(/.+)?$ /yeecms/mysite.com/backend/web/$1 [L,PT]

RewriteCond %{REQUEST_URI} ^.*$
RewriteRule ^(.*)$ /yeecms/mysite.com/frontend/web/$1


When access front webpage,  at the bottom error displayed:


Recent Comments
No comments found.

Not Found (#404)

Page not found.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

**Comment by laoheimao** [comment]
Following is my .htaccess.
# prevent directory listings
Options -Indexes
# follow symbolic links
Options FollowSymlinks
RewriteEngine on
#RewriteBase /yeecms/mysite.com/

RewriteCond %{REQUEST_URI} ^/admin/$
RewriteRule ^(admin)/$ /$1 [R=301,L]
RewriteCond %{REQUEST_URI} ^/admin
RewriteRule ^admin(/.+)?$ /yeecms/mysite.com/backend/web/$1 [L,PT]

RewriteCond %{REQUEST_URI} ^.*$
RewriteRule ^(.*)$ /yeecms/mysite.com/frontend/web/$1


When access front webpage,  at the bottom error displayed:


Recent Comments
No comments found.

Not Found (#404)

Page not found.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

**Comment by yeesoft** [comment]
The path of Yee CMS is not fixed. All you need is to set Apache config DocumentRoot to Yee CMS directory. Customized configuration of Apache server is not a part of Yee CMS.
