### ISSUE TITLE
Help, how can I install yeecms in a sub-directory under Apache DocumentRoot？

### ISSUE THREAD

**Issue by laoheimao** [yeesoft/yii2-yee-cms#46]
Sorry, I want to installed yeecms in a shared apache enviroment, visit via path http://server-ip-address/yeecms/.  is it possible ?  Thanks!

**Comment by yeesoft** [comment]
Try to find the answer here [https://httpd.apache.org/docs/2.4/howto/](https://httpd.apache.org/docs/2.4/howto/)
