### ISSUE TITLE
yii2-yee-cms is multilingual?

### ISSUE THREAD

**Issue by msoa** [yeesoft/yii2-yee-cms#49]
Hi & first thanks for your efforts, specially for [yii2-multilingual](https://github.com/yeesoft/yii2-multilingual) extension.

yii2-yee-cms is multilingual? If not, in future you want add this capability?

In last too thanks

**Edite:**
After installing and checking the code noticed that [yii2-multilingual](https://github.com/yeesoft/yii2-multilingual) is set nicely.
**Know, how can add other languages?**

Thanks for your efforts

**Edit: Solved**
By set languages in: `common/config/main.php`:
```
.
.
.
        'yee' => [
            'class' => 'yeesoft\Yee',
            'languages' => [
                'en-US' => 'English',
                'fa-IR' => 'Persian',
            ],
.
.
.
        ],
```

**Comment by yeesoft** [comment]
@msoa  yii2-multilingual module is a part of upcoming 0.2.x release. There is no need to use it with 0.1
