### ISSUE TITLE
Problem after installing 0.2.x

### ISSUE THREAD

**Issue by isalcedo** [yeesoft/yii2-yee-cms#51]
When I try to run the migration I got this exception:

`Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Application::languages'`

If I comment languages in common/config/main.php

`return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'bootstrap' => ['comments'],
    'language' => 'en-US',
    /*
    'languages' => [
        'en-US' => 'English',
        'uk' => 'Ukrainian',
    ],
    */`

Migrations run.

**Comment by yeesoft** [comment]
@isalcedo Sorry, 0.2.x in not ready yet, it is under development. Please, wait for release.
