### ISSUE TITLE
Installing instructions are not up-to-date

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#6]
The migrations displayed on the Installing instructions (http://www.yee-soft.com/installing) should be the following:

php yii migrate --migrationLookup=@yeesoft/yii2-yee-core/migrations/,@yeesoft/yii2-yee-auth/migrations/,@yeesoft/yii2-yee-settings/migrations/,@yeesoft/yii2-yee-menu/migrations/,@yeesoft/yii2-yee-user/migrations/,@yeesoft/yii2-yee-translation/migrations/,@yeesoft/yii2-yee-media/migrations/,@yeesoft/yii2-yee-post/migrations/,@yeesoft/yii2-yee-page/migrations/,@yeesoft/yii2-comments/migrations/,@yeesoft/yii2-yee-comment/migrations/,@yeesoft/yii2-yee-seo/migrations/.

By running the migrations displayed here http://www.yee-soft.com/installing I got errors.

**Comment by yeesoft** [comment]
updated.
