### ISSUE TITLE
admin account after install has invalid or empty hash

### ISSUE THREAD

**Issue by frankirox** [yeesoft/yii2-yee-cms#7]
admin account after install has invalid hash.

![empty hash](https://cloud.githubusercontent.com/assets/1335554/14267335/5d3d5ada-fa99-11e5-8deb-9d5a6b1b2a16.JPG)

![empty](https://cloud.githubusercontent.com/assets/1335554/14267354/88030d50-fa99-11e5-99c1-bb4fff7820c8.JPG)

**Comment by frankirox** [comment]
I've solved this problem temporally by copying another hash from another yii2 installation, but I'm trying to change the password and it's not possible in frontend/or backend, does nothing.

**Comment by yeesoft** [comment]
@frankirox  I added tool that allow to init root user after application instalation.

Please, check 6th step of https://github.com/yeesoft/yii2-yee-cms/blob/master/README.md

Please, check if you have this new file https://github.com/yeesoft/yii2-yee-cms/blob/master/console/controllers/InitAdminController.php in your application in /console/controllers/ folder
